config/routes.rb
Rails.application.routes.draw do
  resources :sprints
  resources :backlog_items
  get '/backlog_items/:id/up', to: 'backlog_items#up', as: 'up'
  get '/backlog_items/:id/down', to: 'backlog_items#down', as: 'down'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backlog_item.rb
class BacklogItem < ApplicationRecord

  include RankedModel

  ranks :row_order

  belongs_to :sprint

  # ranks :sprint_order_position,
  #    :with_same => :sprint_id

end

app/models/sprint.rb
class Sprint < ApplicationRecord

  has_many :backlog_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backlog_items_controller.rb
class BacklogItemsController < ApplicationController
  before_action :set_backlog_item, only: [:show, :edit, :update, :destroy]

  # GET /backlog_items
  # GET /backlog_items.json
  def index
    @backlog_items = BacklogItem.rank(:row_order).all
  end

  # GET /backlog_items/1
  # GET /backlog_items/1.json
  def show
  end

  # GET /backlog_items/new
  def new
    @backlog_item = BacklogItem.new
  end

  # GET /backlog_items/1/edit
  def edit
  end

  # POST /backlog_items
  # POST /backlog_items.json
  def create
    @backlog_item = BacklogItem.new(backlog_item_params)

    respond_to do |format|
      if @backlog_item.save
        format.html { redirect_to @backlog_item, notice: 'Backlog item was successfully created.' }
        format.json { render :show, status: :created, location: @backlog_item }
      else
        format.html { render :new }
        format.json { render json: @backlog_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlog_items/1
  # PATCH/PUT /backlog_items/1.json
  def update
    respond_to do |format|
      if @backlog_item.update(backlog_item_params)
        format.html { redirect_to @backlog_item, notice: 'Backlog item was successfully updated.' }
        format.json { render :show, status: :ok, location: @backlog_item }
      else
        format.html { render :edit }
        format.json { render json: @backlog_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def up
    set_backlog_item
    @backlog_item.update_attribute :row_order_position, :up
    redirect_to backlog_items_path
  end

  def down
    set_backlog_item
    @backlog_item.update_attribute :row_order_position, :down
    redirect_to backlog_items_path
  end

  # DELETE /backlog_items/1
  # DELETE /backlog_items/1.json
  def destroy
    @backlog_item.destroy
    respond_to do |format|
      format.html { redirect_to backlog_items_url, notice: 'Backlog item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog_item
      @backlog_item = BacklogItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_item_params
      params.require(:backlog_item).permit(:title, :sprint_id)
    end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_sprint, only: [:show, :edit, :update, :destroy]

  # GET /sprints
  # GET /sprints.json
  def index
    @sprints = Sprint.all
  end

  # GET /sprints/1
  # GET /sprints/1.json
  def show
  end

  # GET /sprints/new
  def new
    @sprint = Sprint.new
  end

  # GET /sprints/1/edit
  def edit
  end

  # POST /sprints
  # POST /sprints.json
  def create
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to @sprint, notice: 'Sprint was successfully created.' }
        format.json { render :show, status: :created, location: @sprint }
      else
        format.html { render :new }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprints/1
  # PATCH/PUT /sprints/1.json
  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to @sprint, notice: 'Sprint was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprint }
      else
        format.html { render :edit }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to sprints_url, notice: 'Sprint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_params
      params.require(:sprint).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backlog_items_helper.rb
module BacklogItemsHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/backlog_items/_form.html.erb
<%= form_with(model: backlog_item, local: true) do |form| %>
  <% if backlog_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(backlog_item.errors.count, "error") %> prohibited this backlog_item from being saved:</h2>

      <ul>
      <% backlog_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :title %>
    <%= form.collection_select :sprint_id, Sprint.all, :id, :title %>
    <%= form.submit %>
  </div>
<% end %>

app/views/backlog_items/edit.html.erb
<h1>Editing Backlog Item</h1>

<%= render 'form', backlog_item: @backlog_item %>

<%= link_to 'Show', @backlog_item %> |
<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Backlog Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @backlog_items.each do |backlog_item| %>
      <tr>
        <td><%= link_to "#{backlog_item.title}", backlog_item %></td>
        <td><%= link_to 'Edit', edit_backlog_item_path(backlog_item) %></td>
        <td><%= link_to 'Move Up', up_path(backlog_item) %></td>
        <td><%= link_to 'Move Down', down_path(backlog_item) %></td>
        <td><%= link_to 'Destroy', backlog_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backlog Item', new_backlog_item_path %>

app/views/backlog_items/new.html.erb
<h1>New Backlog Item</h1>

<%= render 'form', backlog_item: @backlog_item %>

<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_backlog_item_path(@backlog_item) %> |
<%= link_to 'Back', backlog_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RankTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sprints/_form.html.erb
<%= form_with(model: sprint, local: true) do |form| %>
  <% if sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% sprint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :title %>
    <%= form.submit %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<h1>Editing Sprint</h1>

<%= render 'form', sprint: @sprint %>

<%= link_to 'Show', @sprint %> |
<%= link_to 'Back', sprints_path %>

app/views/sprints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sprints</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sprints.each do |sprint| %>
      <tr>
        <td><%= link_to "#{sprint.title}", sprint %></td>
        <td><%= link_to 'Edit', edit_sprint_path(sprint) %></td>
        <td><%= link_to 'Destroy', sprint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sprint', new_sprint_path %>

app/views/sprints/new.html.erb
<h1>New Sprint</h1>

<%= render 'form', sprint: @sprint %>

<%= link_to 'Back', sprints_path %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>